"""
Django settings for registration project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p@2zql1%^n4pcof(#)8&^_+$d3#qav^_e79w@#p+76_fyz2hxl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app1',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.discord',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.microsoft',
    'allauth.socialaccount.providers.tiktok',
    'allauth.socialaccount.providers.twitch',
    'allauth.socialaccount.providers.spotify',
    'allauth.socialaccount.providers.telegram',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.discord.DiscordOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.microsoft.MicrosoftOAuth2',
    'social_core.backends.spotify.SpotifyOAuth2',
    'social_core.backends.twitch.TwitchOAuth2',
)


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'registration.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'registration.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Asegúrate de que este sea el directorio correcto
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/login/'

ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tu_email@gmail.com'
EMAIL_HOST_PASSWORD = 'tu_contraseña'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '608426878875-krv80371q1shssv0surv6vg8gnmqlg90.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    },
    'facebook': {
        'APP': {
            'client_id': '3439369163025968',
            'secret': '1a5ecca9e2f20a8ecd4cbdba023c140fs',
            'key': ''
        }
    },
    'discord': {
        'APP': {
            'client_id': '1298096553420132373',
            'secret': 'CS0tpKHOzVlcmmrSBbo3Wnkln0QSKhD4',
            'key': ''
        }
    },
    'twitter': {
        'APP': {
            'client_id': 'Hi8WFvLVuAePXPFHeKNaLGnBH',
            'secret': 'J23elqJrgN63RXIiOTOqZviUfuG2Uwwp60q3w0pwem17Yy9sed',
            'key': ''
        }
    },
    'microsoft': {
        'APP': {
            'client_id': '6533b9e4-ba6c-401b-a479-c80cb41ae403', 
            'secret': 'sqd8Q~yyGDxC3a03QIEyJGsSexYZTu6zoaPYMaxt', 
            'key': ''
        },
        'AUTH_PARAMS': {
            'redirect_uri': 'http://localhost:8000/accounts/microsoft/login/callback/',
        },
    },
    'tiktok': {
        'APP': {
            'client_id': 'awjdw6ymj2ihq345',
            'secret': 'X3JstrP4OSqXIJSujgqyI35E3u04lWZR',
            'key': ''
        }
    },
    'twitch': { 
        'APP': {
            'client_id': '1efoeae4zt6p55d30uyco6s9snc0ha',  
            'secret': 'q3ucgnmqdfbzje1vphc9qmppmocnhw',  
            'key': ''
        },
        'AUTH_PARAMS': {
            'redirect_uri': 'http://localhost:8000/accounts/twitch/login/callback/',
        },
    },
    'spotify': {
        'APP': {
            'client_id': '06f53fb75a4e4b9481b801659eed77de', 
            'secret': 'ac36b18d97ce4dde90ecd62bb6377e06', 
            'key': ''
        },
        'AUTH_PARAMS': {
            'redirect_uri': 'http://localhost:8000/accounts/spotify/login/callback/',  
        },
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')